# Generated by Django 3.1.1 on 2020-12-02 16:00

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgprofile',
            name='city_work',
        ),
        migrations.RemoveField(
            model_name='orgprofile',
            name='position_work',
        ),
        migrations.AlterField(
            model_name='orgprofile',
            name='w_polic_regulations',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('No', 'لا يوجد'), ('Code of conduct', 'مدونة السلوك'), ('Child protection', 'حماية الطفل'), ('Anti-corruption', 'مكافحة الفساد'), ('Human resources policy', 'سياسة الموارد البشرية'), ('Procurement policy', 'سياسة المشتريات'), ('Volunteering policy', 'سياسة التطوع'), ('Anti-harassment Policy', 'سياسة منع التحرش'), ('Financial policy', 'السياسة المالية'), ('Equipment use Policy', 'سياسة استخدام المعدات'), ('privacy policy', 'سياسة الخصوصية'), ('Other', 'أخرى')], max_length=200, verbose_name='السياسات واللوائح المكتوبة'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_work', django_countries.fields.CountryField(max_length=255, verbose_name='مكان العمل')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('city_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.city', verbose_name='المحافظة')),
            ],
        ),
        migrations.AddField(
            model_name='orgprofile',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.position', verbose_name='مكان العمل'),
        ),
    ]
