# Generated by Django 3.1.1 on 2020-11-05 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgjob',
            name='job_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.city', verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='orgnews',
            name='org_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.orgprofile', verbose_name='اسم المنظمة'),
        ),
    ]
