# Generated by Django 3.1.1 on 2020-12-02 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0002_auto_20201202_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='org_id',
            field=models.IntegerField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اسم المستخدم'),
        ),
    ]
