# Generated by Django 3.1.1 on 2020-11-06 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_auto_20201105_1940'),
        ('orgs', '0002_auto_20201105_0049'),
    ]

    operations = [
    ]
