# Generated by Django 3.1.1 on 2020-11-07 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0004_merge_20201106_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgjob',
            name='dead_date',
            field=models.DateField(default=None, verbose_name='تاريخ إغلاق الوظيفة'),
        ),
        migrations.AlterField(
            model_name='orgjob',
            name='org_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.orgprofile', verbose_name='اسم المنظمة'),
        ),
        migrations.CreateModel(
            name='OtherOrgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_org_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المنظمة اﻷخرى')),
                ('logo', models.ImageField(blank=True, default='org_logos/default_logo.jpg', null=True, upload_to='other_org_logos', verbose_name='شعار المنظمة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orgjob',
            name='other_org_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.otherorgs'),
        ),
    ]
