# Generated by Django 3.1.1 on 2020-11-07 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_auto_20201107_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherorgs',
            old_name='other_org_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='orgjob',
            name='other_org_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.otherorgs', verbose_name='اسم المنظمة اﻷخرى'),
        ),
    ]
