# Generated by Django 3.1.1 on 2020-12-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_auto_20201202_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='devorgopp',
            name='staff',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orgcapacityopp',
            name='staff',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orgdata',
            name='staff',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orgfundingopp',
            name='staff',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orgjob',
            name='staff',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orgmedia',
            name='staff',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orgnews',
            name='staff',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orgrapport',
            name='staff',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orgresearch',
            name='staff',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='persfundingopp',
            name='staff',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orgprofile',
            name='logo',
            field=models.ImageField(blank=True, default='org_logos/default_logo.jpg', null=True, upload_to='org_logos', verbose_name='شعار المنظمة'),
        ),
    ]
