# Generated by Django 3.1.1 on 2020-12-04 11:54

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0007_auto_20201202_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgnews',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=5000, verbose_name='تفاصيل الخبر'),
        ),
        migrations.AlterField(
            model_name='orgprofile',
            name='message',
            field=ckeditor.fields.RichTextField(max_length=2000, verbose_name='الرؤية و الرسالة'),
        ),
        migrations.AlterField(
            model_name='orgprofile',
            name='user',
            field=models.ForeignKey(blank=True, help_text='المستخدمين الذين ليس لديهم طلبات بروفايل فقط', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اسم المستخدم'),
        ),
    ]
