# Generated by Django 3.1.1 on 2020-12-04 14:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0008_auto_20201204_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devorgopp',
            name='dev_description',
            field=ckeditor.fields.RichTextField(max_length=5000, verbose_name='لمحة عن الجهة'),
        ),
        migrations.AlterField(
            model_name='orgcapacityopp',
            name='capacity_description',
            field=ckeditor.fields.RichTextField(max_length=5000, verbose_name='وصف الفرصة'),
        ),
        migrations.AlterField(
            model_name='orgcapacityopp',
            name='capacity_guid',
            field=ckeditor.fields.RichTextField(max_length=5000, verbose_name='طريقة التقديم'),
        ),
        migrations.AlterField(
            model_name='orgcapacityopp',
            name='capacity_reqs',
            field=ckeditor.fields.RichTextField(max_length=5000, verbose_name='متطلبات التقديم'),
        ),
        migrations.AlterField(
            model_name='orgfundingopp',
            name='funding_conditions',
            field=ckeditor.fields.RichTextField(max_length=5000, verbose_name='شروط المنحة'),
        ),
        migrations.AlterField(
            model_name='orgfundingopp',
            name='funding_description',
            field=ckeditor.fields.RichTextField(max_length=5000, verbose_name='وصف المنحة'),
        ),
        migrations.AlterField(
            model_name='orgfundingopp',
            name='funding_guid',
            field=ckeditor.fields.RichTextField(max_length=5000, verbose_name='كيفية التقديم'),
        ),
        migrations.AlterField(
            model_name='orgfundingopp',
            name='funding_org_description',
            field=ckeditor.fields.RichTextField(max_length=5000, verbose_name='لمحة عن الجهة المانحة'),
        ),
        migrations.AlterField(
            model_name='orgfundingopp',
            name='funding_reqs',
            field=ckeditor.fields.RichTextField(max_length=5000, verbose_name='متطلبات التقديم'),
        ),
        migrations.AlterField(
            model_name='orgjob',
            name='job_aplay',
            field=ckeditor.fields.RichTextField(max_length=5000, verbose_name='طريقة التقدم للوظيفة'),
        ),
        migrations.AlterField(
            model_name='orgjob',
            name='job_description',
            field=ckeditor.fields.RichTextField(max_length=5000, verbose_name='وصف الوظيفة'),
        ),
        migrations.AlterField(
            model_name='orgprofile',
            name='message',
            field=ckeditor.fields.RichTextField(max_length=5000, verbose_name='الرؤية و الرسالة'),
        ),
        migrations.AlterField(
            model_name='persfundingopp',
            name='fund_org_description',
            field=ckeditor.fields.RichTextField(max_length=5000, verbose_name='لمحة عن الجهة المانحة'),
        ),
        migrations.AlterField(
            model_name='persfundingopp',
            name='funding_conditions',
            field=ckeditor.fields.RichTextField(max_length=5000, verbose_name='شروط المنحة'),
        ),
        migrations.AlterField(
            model_name='persfundingopp',
            name='funding_description',
            field=ckeditor.fields.RichTextField(max_length=5000, verbose_name='وصف المنحة'),
        ),
        migrations.AlterField(
            model_name='persfundingopp',
            name='funding_guid',
            field=ckeditor.fields.RichTextField(max_length=5000, verbose_name='كيفية التقديم'),
        ),
        migrations.AlterField(
            model_name='persfundingopp',
            name='funding_reqs',
            field=ckeditor.fields.RichTextField(max_length=5000, verbose_name='متطلبات التقديم'),
        ),
    ]
