# Generated by Django 3.1.1 on 2020-12-07 14:31

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0009_auto_20201204_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position_work',
            field=django_countries.fields.CountryField(blank=True, max_length=255, null=True, verbose_name='مكان العمل'),
        ),
    ]
