# Generated by Django 3.1.1 on 2020-11-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0009_auto_20201107_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherorgs',
            name='job',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
