# Generated by Django 3.1.1 on 2020-11-08 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0010_otherorgs_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgfundingopp',
            old_name='funding_country',
            new_name='position_work',
        ),
        migrations.RemoveField(
            model_name='orgfundingopp',
            name='funding_city',
        ),
        migrations.AddField(
            model_name='orgfundingopp',
            name='city_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.city', verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='orgfundingopp',
            name='logo',
            field=models.ImageField(default='org_logos/default_logo.jpg', upload_to='funding_logos', verbose_name='لوغو الجهة المانحة'),
        ),
        migrations.AlterField(
            model_name='orgfundingopp',
            name='funding_description',
            field=models.TextField(max_length=2000, verbose_name='وصف المنحة'),
        ),
        migrations.AlterField(
            model_name='orgfundingopp',
            name='name_funding',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الجهة المانحة'),
        ),
        migrations.AlterField(
            model_name='orgfundingopp',
            name='org_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.orgprofile', verbose_name='اسم المنظمة'),
        ),
    ]
