# Generated by Django 3.1.1 on 2020-11-08 21:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0011_auto_20201108_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgfundingopp',
            name='funding_amounte',
            field=models.CharField(choices=[('less than 5000 ', 'أقل من 5000 دولار'), ('from 5000 to 10000 dollar', 'بين 5000 و 10000 دولار'), ('from 10000 to 50000', 'بين 10000 و50000 دولار'), ('from 50000 to 100000', 'بين 50000 و100000 دولار'), ('more than  100000', 'بين 50000 و100000 دولار'), ('other', 'أخرى')], default=django.utils.timezone.now, max_length=255, verbose_name=' حجم المنحة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orgfundingopp',
            name='funding_dead_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ إغلاق المنحة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orgfundingopp',
            name='funding_period',
            field=models.CharField(choices=[('less of 6 months', 'أقل من 6 أشهر'), ('from 6 mths to one year', 'ستة أشهر لسنة'), ('from one to 2 years', 'سنة إلى سنتين'), ('more than 2 years', 'أكثر من سنتين'), ('other', 'أخرى')], default=django.utils.timezone.now, max_length=255, verbose_name='مدة المنحة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orgfundingopp',
            name='logo',
            field=models.ImageField(blank=True, default='org_logos/default_logo.jpg', null=True, upload_to='funding_logos', verbose_name='لوغو الجهة المانحة'),
        ),
    ]
