# Generated by Django 3.1.1 on 2020-11-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0012_auto_20201108_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgfundingopp',
            name='funding_dead_date',
            field=models.DateField(verbose_name='تاريخ إغلاق المنحة'),
        ),
    ]
