# Generated by Django 3.1.1 on 2020-11-09 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0013_auto_20201108_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgfundingopp',
            name='funding_amounte',
            field=models.CharField(choices=[('less than 5000 ', 'أقل من 5000 دولار'), ('from 5000 to 10000 dollar', 'بين 5000 و 10000 دولار'), ('from 10000 to 50000', 'بين 10000 و50000 دولار'), ('from 50000 to 100000', 'بين 50000 و100000 دولار'), ('more than  100000', 'بين 50000 و100000 دولار'), ('other', 'أخرى')], max_length=255, verbose_name='حجم المنحة'),
        ),
        migrations.CreateModel(
            name='PersFundingOpp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_funding', models.CharField(blank=True, max_length=255, null=True, verbose_name='الجهة المانحة')),
                ('logo', models.ImageField(blank=True, default='org_logos/default_logo.jpg', null=True, upload_to='funding_logos', verbose_name='لوغو الجهة المانحة')),
                ('category', models.CharField(blank=True, choices=[('total', 'كلية'), ('part', 'جزئية')], max_length=100, null=True, verbose_name='فئة المنحة')),
                ('fund_type', models.CharField(choices=[('study', 'دراسية'), ('prod', 'انتاجية'), ('study & reserch', 'دراسات و أبحاث')], max_length=150, verbose_name='نوع المنحة')),
                ('study_level', models.CharField(blank=True, choices=[('licence', 'إجازة جامعية'), ('m1', 'دبلوم'), ('m2', 'ماجيستير'), ('doctorat', 'دكتوراه')], max_length=255, null=True, verbose_name='المستوى التعليمي')),
                ('comp_study', models.CharField(blank=True, choices=[('1', 'إعلام/ اتصالات/ علاقات عامة'), ('2', 'أعمال وإدارة'), ('3', 'اقتصاد/ محاسبة'), ('4', 'تعليم/ تربية/ رياض أطفال'), ('5', 'حاسوب وتكنولوجيا المعلومات'), ('6', 'دراسات إسلامية'), ('7', 'دراسات إنسانية/ لغات'), ('8', 'زراعة وعلوم بيئية'), ('9', 'سياحة وعلوم فندقية'), ('10', 'علوم إنسانية'), ('11', 'علوم طبية/ طب/ صيدلة/ تمريض'), ('12', 'علوم طبيعية'), ('13', 'عمارة وتصميم'), ('14', 'فنون ومسارح وموسيقى'), ('15', 'قانون ودراسات قانونية'), ('16', 'هندسة وعلوم هندسية')], max_length=255, null=True, verbose_name='الاختصاص التعليمي')),
                ('domain', models.CharField(blank=True, choices=[('Media', 'إعلام'), ('Education', 'تعليم'), ('Protection', 'حماية'), ('Livelihoods and food security', 'سبل العيش واﻷمن الغذائي'), ('Project of clean ,water, sanitation ', 'مشاريع النظافة والمياه والصرف الصحي'), ('Development', 'تنمية'), ('Law, suport, policy', 'قانون و مناصرة و سیاسة'), ('Donors and support volunteering', 'مانحین و دعم العمل التطوعي'), ('Religious org', 'منظمات دینیة'), ('Prof association and assembles', 'تجمعات و اتحادات مھنیة'), ('Health', 'صحة'), ('Studies and research', 'دراسات وأبحاث'), ('Other', 'أخرى')], max_length=255, null=True, verbose_name='قطاع المنحة')),
                ('position_work', django_countries.fields.CountryField(max_length=255, verbose_name='دول المنحة')),
                ('fund_org_description', models.TextField(max_length=5000, verbose_name='لمحة عن الجهة المانحة')),
                ('funding_dead_date', models.DateField(verbose_name='تاريخ إغلاق المنحة')),
                ('funding_period', models.CharField(choices=[('less of 6 months', 'أقل من 6 أشهر'), ('from 6 mths to one year', 'ستة أشهر لسنة'), ('from one to 2 years', 'سنة إلى سنتين'), ('more than 2 years', 'أكثر من سنتين'), ('other', 'أخرى')], max_length=255, verbose_name='مدة المنحة')),
                ('funding_amounte', models.CharField(choices=[('less than 5000 ', 'أقل من 5000 دولار'), ('from 5000 to 10000 dollar', 'بين 5000 و 10000 دولار'), ('from 10000 to 50000', 'بين 10000 و50000 دولار'), ('from 50000 to 100000', 'بين 50000 و100000 دولار'), ('more than  100000', 'بين 50000 و100000 دولار'), ('other', 'أخرى')], max_length=255, verbose_name='حجم المنحة')),
                ('funding_description', models.TextField(max_length=2000, verbose_name='وصف المنحة')),
                ('funding_conditions', models.TextField(max_length=2000, verbose_name='شروط المنحة')),
                ('funding_reqs', models.TextField(max_length=2000, verbose_name='متطلبات التقديم')),
                ('funding_guid', models.TextField(max_length=2000, verbose_name='كيفية التقديم')),
                ('funding_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='الرابط الأصلي')),
                ('publish', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('city_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.city', verbose_name='المحافظة')),
                ('org_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.orgprofile', verbose_name='اسم المنظمة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
