# Generated by Django 3.1.1 on 2020-11-10 01:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0015_auto_20201109_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgcapacityopp',
            old_name='capacity_country',
            new_name='position_work',
        ),
        migrations.RemoveField(
            model_name='orgcapacityopp',
            name='capacity_city',
        ),
        migrations.AddField(
            model_name='orgcapacityopp',
            name='city_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.city', verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='orgcapacityopp',
            name='capacity_dead_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ إغلاق المنحة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orgcapacityopp',
            name='name_capacity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الجهة الممولة'),
        ),
        migrations.AlterField(
            model_name='orgcapacityopp',
            name='org_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.orgprofile', verbose_name='اسم المنظمة'),
        ),
    ]
