# Generated by Django 3.1.1 on 2020-11-10 04:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0016_auto_20201110_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='devorgopp',
            name='content',
            field=models.FileField(blank=True, default='org_logos/default_logo.jpg', null=True, upload_to='dev_files', verbose_name='المادة '),
        ),
        migrations.AddField(
            model_name='devorgopp',
            name='subject',
            field=models.CharField(choices=[('Project development and management', 'تطوير وإدارة المشاريع'), ('Organizational governance', 'الحوكمة التنظيمية'), ('Advocacy and Campaigns', 'المناصرة والحملات'), ('Civil Society Library', 'مكتبة المجتمع المدني'), ('other', 'أخرى')], default=django.utils.timezone.now, max_length=255, verbose_name='موضوع المادة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devorgopp',
            name='name_dev',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الجهة '),
        ),
        migrations.AlterField(
            model_name='orgcapacityopp',
            name='capacity_description',
            field=models.TextField(max_length=5000, verbose_name='وصف الفرصة'),
        ),
    ]
