# Generated by Django 3.1.1 on 2020-11-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_auto_20201110_0204'),
        ('orgs', '0017_auto_20201110_0402'),
    ]

    operations = [
    ]
