# Generated by Django 3.1.1 on 2020-11-10 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0018_merge_20201110_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgnews',
            name='org_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.orgprofile', verbose_name='اسم المنظمة'),
        ),
    ]
