# Generated by Django 3.1.1 on 2020-11-10 20:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0020_auto_20201110_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgprofile',
            name='message',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='الرؤية و الرسالة'),
        ),
    ]
