# Generated by Django 3.1.1 on 2020-11-11 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0021_auto_20201110_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='devorgopp',
            name='video',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='رابط فيديو'),
        ),
        migrations.AlterField(
            model_name='devorgopp',
            name='org_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.orgprofile', verbose_name='اسم المنظمة'),
        ),
    ]
